default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bus_development

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: bus_production
